### ISSUE TITLE
Images in "Thinking in React" are too small

### ISSUE THREAD

**Issue by gaearon** [reactjs/reactjs.org#174]
They used to look more readable than this:

<img width="788" alt="screen shot 2017-10-17 at 9 32 22 pm" src="https://user-images.githubusercontent.com/810438/31687985-bad2c718-b382-11e7-8bfa-357126861a15.png">

**Comment by ismamz** [comment]
Hi @gaearon, it seems like Gatsby resize images to show on HD displays. Do you think it's necessary to export the images with high resolution? Or just resize them?

By the way, the lists don't have left padding (in your image for example), is this right? I've submit a pull request fixing that, but maybe it's good for you those styles.

**Comment by KyleAMathews** [comment]
Probably related to this unfortunately :-(

https://github.com/gatsbyjs/gatsby/issues/2292

**Comment by bvaughn** [comment]
Thanks for reporting this Dan! It was on my list during early development and I somehow forgot to file it.

And thanks for the link to the associated Gatsby issue, Kyle!

**Comment by KyleAMathews** [comment]
This was fixed by @bripkens in https://github.com/gatsbyjs/gatsby/pull/2713

**Comment by bvaughn** [comment]
Cool beans. Thanks for the update, @KyleAMathews!

**Comment by bvaughn** [comment]
Fixed by upgrading Gatsby and co. (9f46dbe8c)

### Before
<img width="738" alt="screen shot 2017-11-09 at 2 53 00 pm" src="https://user-images.githubusercontent.com/29597/32611511-d0215156-c55d-11e7-8c0e-34835a56fbaf.png">

### After
<img width="736" alt="screen shot 2017-11-09 at 2 52 56 pm" src="https://user-images.githubusercontent.com/29597/32611515-d26f1510-c55d-11e7-8553-9456623ec2d9.png">
