### ISSUE TITLE
Major version LTS dates

### ISSUE THREAD

**Issue by nircha** [reactjs/reactjs.org#1745]
I was wondering what is the Long term support policy for major versions, e.g. , if version 16.0 was released on September 2017, until when do you keep resolving bugs on version 15? or porting resolved bugs from version 16 back to version 15?(if applicable of course)

**Comment by gaearon** [comment]
Once a new major is released, we generally stop releasing new fixes for a previous major. The only exception is absolutely critical bugs (including security vulnerabilities).

**Comment by aaronfrost** [comment]
@gaearon in the exception you called out above, for the sake of clarity, how long is it expected that the team would continue to address "critical bugs" and/or "security vulnerabilities"?

I suppose for the sake of begging out what I am looking for, if tonight we found a critical security issue in the codebase that affects even the first version of React and every version since... which versions would the team patch with the fix? My clients are asking me how long they can expect this kind of LTS from Facebook. Is it only for the latest versions? If not, how far back would the team consider patching? How would that decision be made?
