### ISSUE TITLE
Update docs to use hooks

### ISSUE THREAD

**Issue by selbekk** [reactjs/reactjs.org#1788]
As of now, the main docs haven’t been updated to account for hooks. Especially the state & lifecycle section seems a bit misleading now.

I’d love to help out with a rewrite, but I’d love to hear your feedback on what should be changed and what should stay behind.

**Comment by saranshkataria** [comment]
Since we are having the discussion at #1782, closing this one out.

**Comment by selbekk** [comment]
Slightly different issue @saranshkataria - this pertains to the docs, not the tutorial

**Comment by saranshkataria** [comment]
ah, my bad. But why would we want everything to be hooks in the docs? There's a section about hooks and that is what it should be?

**Comment by selbekk** [comment]
On mobile now, but in short: if the Preferred Way of React going forward is using hooks for stuff like state and side effects, I think we should rewrite the docs so that they mirror that message. Right now, that’s not the case.

Have a look here: https://reactjs.org/docs/state-and-lifecycle.html

Class components and lifecycles definitely need to be documented, but perhaps not as... «the first choice», if you know what i mean.

**Comment by saranshkataria** [comment]
I don't think the docs should be preferring one way over the other yet, everyone is still figuring hooks out, but will reopen this issue to let other people share their opinions on it.

**Comment by selbekk** [comment]
As of now, though, the docs _are_ preferring class components, by not even mentioning hooks (at least in that section)

**Comment by kachkaev** [comment]
RADME.md in facebook/react repo [says](https://github.com/facebook/react/blob/master/README.md#examples): 

> We have several examples [on the website](https://reactjs.org/). Here is the first one to get you started: 
> [a functional component]

Following the link takes a newcomer to a page where all components are classes. This is quite confusing. Given that the stateful logic can be expressed using functions now, classes can be revealed much later.

**Comment by voluntadpear** [comment]
I feel the same about the Main Concepts docs. Especially the "State and Lifecycle" doc. I was expecting to see at least a mention about Hooks there. Newcomers to React (especially folks coming from other libraries) could choose to check the Docs instead of the Tutorial (depending on their style of learning) so the Hooks section being after Advanced Guides and even the API Reference makes them somehow easy to miss. Having a brief mention of Hooks as an alternative to classes could be really helpful.

**Comment by nickmccurdy** [comment]
@saranshkataria 
> I don't think the docs should be preferring one way over the other yet, everyone is still figuring hooks out, but will reopen this issue to let other people share their opinions on it.
The hooks docs specifically recommend using hooks rather than classes for new components. The docs should primarily focus on hooks to be consistent with this suggestion, and save time by not requiring users to learn classes before they can learn hooks.

With docs rewritten in hooks, we'd have to decide how to handle the old hooks docs. Is the class API going to change in the future, making it useful to retain separate class docs? If not, should we stop updating the class docs or treat them as a different version (in the version switcher) or subsection of the hooks docs (kinda like how the hooks are a subsection of the classes docs now)?

**Comment by nickmccurdy** [comment]
I'm making progress on converting the docs to use hooks instead of classes, and I'll submit a pull request when it's mostly complete. Then we can figure out if it's okay to replace the class docs or if the hook docs should be reworked in a different way.

**Comment by nickmccurdy** [comment]
I've started a draft pull request, I'm not done checking it for accuracy but I'd still appreciate feedback: https://github.com/reactjs/reactjs.org/pull/2400

**Comment by jasongi-actu** [comment]
Since hooks are such a big change, and many people will be needing to learn react using classes, is it an option to provide examples, one using hooks and one using classes? Perhaps tab separated or something? I think this would also aid with people who want to refactor class code to functional components, as well as ensuring new code projects and people new to react start off learning hooks.

**Comment by nickmccurdy** [comment]
I don’t think that’s a good idea because the hook API is designed very differently. There’s some overlap with some usages of hooks and classes, but there are enough differences and quirks that I think it would be easiest to explain them separately. There are already some references that compare basic hook usage with basic class usage anyway. 

That being said, I’ve stopped working on this as it’s too much work for me alone to make the existing docs make sense for hooks, and the React team is planning on rewriting them from scratch anyway.

**Comment by karlhorky** [comment]
In case this can be useful to anyone else:

@nickmccurdy's incomplete but very useful version of the docs with React hooks is online at https://reacthooks.nickmccurdy.com

**Comment by kachkaev** [comment]
@karlhorky this might be a bit off-topic, but do you know why it‘s 

```tsx
function HelloMessage(props) {
  return <div>Hello {props.name}</div>;
}
```

and not

```tsx
const HelloMessage = (props) => {
  return <div>Hello {props.name}</div>;
}
```
?

If I were new to JavaScript in 2020, I’d have to learn arrow functions anyway – they are unavoidable. `function` keyword though is what can easily be replaced in the entire codebase with no harm, assuming we don’t rely on `this`.

At our company, we stick with arrow functions everywhere and it works great. The only exception so far is [function overload in typescript](https://www.typescriptlang.org/docs/handbook/functions.html#overloads), which is both advanced and rare. ESLint’s [func-style](https://eslint.org/docs/rules/func-style) helps us stick to the rule pretty well.

Yet, I often see others using `function MyComponent` in React examples and docs. I feel like I’m missing something, because I don’t fully understand this decision. What can I read to fill the gap? Or is this simply an old-school established flavour that people keep using by inertia?

Should not future react docs bet on arrow functions everywhere to reduce the readers’ cognitive load?

**Comment by gaearon** [comment]
Just wanted to note this is still very much on our minds. We might start looking into this soon-ish. One challenge is how to coordinate translations. Since this is a big rewrite. cc @tesseralis curious if you have tips on how we could approach this.

**Comment by kachkaev** [comment]
@gaearon when replacing class components with the function ones in the docs, are you going to use `function MyComponent() {}` or `const MyComponent = () => {}`? I guess that there should be some agreed on guidelines before the process starts. The chosen flavour has a pretty significant impact on the community IMHO, so it should be picked very carefully.

**Comment by gaearon** [comment]
I don't think there would be any significant impact given we've used `function` since 2013 and people sometimes prefer arrows anyway.

**Comment by tesseralis** [comment]
@gaearon I don't think there should be a significant problem, although it might cause a headache with some languages that aren't as active. I'll check in over the weekend and see if there are any issues and see what's the best way to communicate this change to people.

**Comment by koba04** [comment]
I think "Tutorial" is the highest priority than others because beginners would check the Tutorial page first. I cannot recommend beginners the current Tutorial page because the Tutorial is written based on class components.
I believe that React is going forward to the Hooks world, so I'd like to teach beginners how to create components with Hooks at first rather than class components API even though they might learn class components API for existing components later.

It needs many works for translation, but it shouldn't block the migration.

**Comment by nickmccurdy** [comment]
If anyone's interested, there's a newer fork of the docs that's more up to date than mine: https://reactwithhooks.netlify.app/

**Comment by harish-sethuraman** [comment]
React documentation is currently being rewritten from scratch and is a WIP.
Do checkout https://beta.reactjs.org and let us know your feedback in the following issue :)
- https://github.com/reactjs/reactjs.org/issues/3308
