### ISSUE TITLE
useEffect documentation and misunderstandings

### ISSUE THREAD

**Issue by tmcw** [reactjs/reactjs.org#1945]
In our application, we ran into a bug related to using a `[]` array as the second argument to `useEffect`, on the assumption that it would only run on mount and unmount. Unfortunately, this wasn't true and produced some chaos.

That bug was fixable, albeit not very cleanly, but it led me to notice a few things:

> When exactly does React clean up an effect? React performs the cleanup when the component unmounts. However, as we learned earlier, effects run for every render and not just once. This is why React also cleans up effects from the previous render before running the effects next time. We’ll discuss why this helps avoid bugs and how to opt out of this behavior in case it creates performance issues later below.

This could be clearer by saying:

> When exactly does React clean up an effect? React performs the cleanup when the component unmounts, and also between renders. As we learned earlier, effects run for every render and not just once. This is why React also cleans up effects from the previous render before running the effects next time. We’ll discuss why this helps avoid bugs and how to opt out of this behavior in case it creates performance issues later below.

This misunderstanding is fairly widespread: for example,

- on [useHooks.com](https://usehooks.com/), in each of its examples featuring useEffect, it has a comment `Empty array ensures effect is only run on mount and unmount`. 
- in [React Hooks: Why and How](https://medium.com/frontmen/react-hooks-why-and-how-e4d2a5f0347#95dc), it states "Optionally the second parameter can also just be an empty array, in this case it will only execute on componentDidMount and componentWillUnmount and the effect won’t run on componentDidUpdate."
- In [Using the useEffect hook](https://www.leighhalliday.com/use-effect-hook), it states "Let's say we only wanted the effect to run a single time... think of this as a replacement for componentDidMount. To do this, pass a [] as the 2nd argument to useEffect:"

Certainly a lot of this misunderstanding is just folks looking for equivalents of the React.Component API, and in this case there isn't a precise one. But I think by saying that there are _two_ cases up-front, rather than saying one and then _also_ the other, you'll help keep people on the right path.

**Comment by gaearon** [comment]
Sorry that this slipped through the cracks. We've been heads down working on the next releases, and have deprioritized GitHub issue maintenance in the docs repo for now. We're also rewriting the docs because a lot of these problems are known (and aren't new), and we want to address them holistically.

I do want to note that this sounds inaccurate:

>`[]` array as the second argument to useEffect, on the assumption that it would only run on mount and unmount [...] this wasn't true

In today's React, an empty `[]` argument *does* exactly correspond to mount/unmount. (Although we try not to advertise it as such because it gives you wrong assumptions about props and state — they will be the initially captured ones instead of continuously updated ones like `this.props` or `this.state` were inside `componentDidMount`.)

So your initial assumption _was_ correct and the problem you've seen must have been something else. I don't know what, though, since there was no reproducing example.
