### ISSUE TITLE
ReactDOM.findDOMNode should be updated with React 16 behavior

### ISSUE THREAD

**Issue by ferdaber** [reactjs/reactjs.org#201]
Back in the dark times of when a render function was only able to return a single element, `ReactDOM.findDOMNode` was predictable in that it will only return one and only one element.

With the introduction of being able to return multiple fragments in React 16, the public API docs should be reflected to clarify that it returns the first fragment in the array.

I'd be happy to submit a PR if folks think this is a good idea.

**Comment by gaearon** [comment]
Sounds great. It can also return null for empty components.

**Comment by bvaughn** [comment]
Thanks for reporting this issue @ferdaber! It's all yours! 😄

I've added an "in-progress" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by bvaughn** [comment]
Whoops. This was fixed via #202 and just never closed.
