### ISSUE TITLE
New to React. Trying to run the Hello World from the Create React App

### ISSUE THREAD

**Issue by dc4444** [reactjs/reactjs.org#217]
I started "Create React App" using npm. I then edited the App.js file - I added the code below for the Hello World and saved it. But it does not work. 

I get: 

```
Failed to compile
./src/App.js
Syntax error: C:/Dans/Work 2/Tech/Web Dev/Javascript and jQuery/Reactjs/my-app/src/App.js: Unexpected token (6:12)

  4 | 
  5 | class App extends Component {
> 6 |     ReactDOM.render(
    |             ^
  7 |       <h1>Hello, world!</h1>,
  8 |       document.getElementById('root')
  9 |     );
This error occurred during the build time and cannot be dismissed.

```
------------------------------

Note: The documentation does not explain how to do the examples using the "Create React App". It works if I follow the section for "Trying Out React". I use my own text editor, using the download HTML file and modifying it for Hello World. See the code at the bottom that works!

------------------------------

I replaced the original code with:

```js
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

class App extends Component {
ReactDOM.render(
  <h1>Hello, world!</h1>,
  document.getElementById('root')
);
}
```

export default App;

--------------------------------------------

The original code:

```js
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
      </div>
    );
  }
}

export default App;
```

-----

It works if I follow the section for "Trying Out React". I use my own text editor, using the download HTML file and modifying it for Hello World.

```html
<!DOCTYPE html>
<html>    
    <head>
        <meta charset="UTF-8" />
        <title>Hello World</title>
              
        <link href="C:\Dans\Work 2\Tech\Web Dev\Javascript and jQuery\Reactjs\Hello world\style.css" rel="stylesheet" type="text/css" />   
    </head>     
    <body>
        <div id="root">
          <!-- This div's content will be managed by React. -->
        </div>        
        <script type="text/babel">
            ReactDOM.render(
               <h1>Hello, world!</h1>,
               document.getElementById('root')
            );
        </script>
    </body> 

    <script crossorigin src="https://unpkg.com/react@16/umd/react.development.js"></script>
    <script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
    <script src="https://unpkg.com/babel-standalone@6.15.0/babel.min.js"></script>
</html>
```

**Comment by gaearon** [comment]
>I then edited the App.js file - I added the code below for the Hello World and saved it. But it does not work.

It would have worked if you edited `src/index.js` instead and just left it:

```js
ReactDOM.render(
  <h1>Hello, world!</h1>,
  document.getElementById('root')
);
```

There was no need to open `App.js` because the concept of components (which App is) was not explained until later. Just trying to put this code inside `class App` could not work.

Do you have ideas on how to fix this in the documentation?

**Comment by bvaughn** [comment]
I'm having a little trouble understanding this feedback.

> It works if I follow the section for "Trying Out React".

It sounds like you're asking for more detail about how to get started with create-react-app. I'm curious if you checked out the ["getting started" documentation for that project](https://github.com/facebookincubator/create-react-app#creating-an-app) and if you think it could be improved any?

We currently link to that documentation from the "Trying Out React" page. I'm hesitant to overlap too much with its documentation because redundant documentation is harder to keep in-sync and up-to-date.

**Comment by dc4444** [comment]
gaearon...that worked...fyi, it would be nice if the instructions stated to add the code to the src/index.js.

**Comment by bvaughn** [comment]
> it would be nice if the instructions stated

Hi @dc4444 👋 Not sure if you saw my question above, but which instructions are you referring to? The ones one reactjs.org or the README for create-react-app?

**Comment by dc4444** [comment]
HI...on reactjs.org




________________________________

**Comment by bvaughn** [comment]
Gotcha. Thanks for clarifying!

My opinion on this is that it does not make sense to add additional instructions to reactjs.org that are specific to the template `create-react-app` uses. We already link to that project's [README](https://github.com/facebookincubator/create-react-app#create-react-app-) which includes things like a "Getting Started" guide.

I think I'll close this issue for now though since I don't personally think we need to take specific action on it. (Happy to continue the conversation here though. Also happy to review PRs that improve the documentation if you have specific suggestions for improvement.)

**Comment by karynew** [comment]
I had the same problem and I fixed this adding "react" in presets configuration like this way inside .babelrc

"presets":[
    "env",
    "react"
  ],
