### ISSUE TITLE
Document requirements for component names in error boundary stack traces

### ISSUE THREAD

**Issue by wKovacs64** [reactjs/reactjs.org#221]
Should the requirements for meaningful component names in error boundary stack traces be documented in either the [JavaScript Environment Requirements](../blob/master/content/docs/reference-javascript-environment-requirements.md) (with the other polyfills) or the [Error Boundaries](../blob/master/content/docs/error-boundaries.md) section (as it's specific to these and polyfilling isn't the only option)?

To quote @Kovensky:
> IE11 does not support Function#name, so all your functions (and thus components) are unnamed unless you either set displayName or polyfill it with a getter in Function.prototype. core-js provides such a polyfill.

Ref: facebook/react#11353

**Comment by bvaughn** [comment]
Hm. I don't really think this belongs in the [JavaScript Environment Requirements](https://github.com/reactjs/reactjs.org/blob/master/content/docs/reference-javascript-environment-requirements.md) section, since it isn't a "requirement" so much as a handy debugging tool.

Perhaps a note could be added under [Component Stack Traces](https://reactjs.org/docs/error-boundaries.html#component-stack-traces)? Would you be willing to submit a PR for this, @wKovacs64?

**Comment by wKovacs64** [comment]
Yeah, that sounds reasonable @bvaughn - thanks. I'll try to throw a PR together.
