### ISSUE TITLE
Best/fastest way to learn React with hooks

### ISSUE THREAD

**Issue by darrenpierre90** [reactjs/reactjs.org#2424]
what's the best way to learn react ? Since there's a new API for HOOK using hooks , I would like to use that from the very start but all the tutorials on learning react still use the old method. So I'm wondering what should I do for learning react and what topics are still revelant

**Comment by ndresx** [comment]
The official introduction (https://reactjs.org/docs/hooks-intro.html) is really good to get to know the basics of Hooks. It also has references back to their class-based equivalents to be able to compare these two concepts.

However, I would still suggest going through React's main concepts first (https://reactjs.org/docs/hello-world.html) because it allows you to understand the fundamentals much better, even if you are going to use Hooks later on!
