### ISSUE TITLE
setState with updater function - general recommendation?

### ISSUE THREAD

**Issue by donaldpipowitch** [reactjs/reactjs.org#257]
Hi, sorry, this is probably a dumb question. Dan once tweeted `it is also actively recommended [to use setState with an updater function] if you're setting state based on previous state`. Many picked this up (me, too) as a general recommendation, but I can't reference an event without `event.persist()` in this updater callback.

So what it the general recommendation?

1) _Only_ use `setState(updaterCallback)` if the state is based on the previous state, but default to `setState(newState)`?
2)  _Only_ use `setState(newState)` if the state is based on an event, but default to `setState(updaterCallback)`?
3) _Always_ try to use `setState(updaterCallback)` and call `event.persist()`, if the state is based on an event.
4) It doesn't matter.
5) ...and what if it neither based on the previous state nor an event...?

**Comment by bvaughn** [comment]
I'm not sure which comment of Dan's you're referring to, but the recommendation to use the updater function is very important if the state update is in any way derived from or based on current (previous) state. Otherwise, I don't think it matters either way. My recommendation, then, would be most similar to option one above.

Some people might suggest more strongly to always use an updater function, to avoid the possibility of someone _forgetting_ or _accidentally_ referencing stale state. As you mention though, using an updater function can introduce its own awkwardness when it comes to the synthetic event system. The solution for this, as you've noted, is to either call `persist()` on the event _or_ just retrieve the value you need from it synchronously (outside of the updater function).

```js
_onSomeEvent = event => {
  const eventValue = event.value;

  this.setState(state => ({
    stateValue: state.someOtherValue + eventValue // This is a silly example
  }));
}
```

**Comment by donaldpipowitch** [comment]
Sorry, I forgot to add a link to Dans tweet. Updated my post.

Thank you for the quick answer. ♥️
