### ISSUE TITLE
yarn link not work when I want to use React from npm in my local project.

### ISSUE THREAD

**Issue by monkindey** [reactjs/reactjs.org#265]
According to [how to contribute](https://reactjs.org/docs/how-to-contribute.html#development-workflow) section: 

> If your project uses React from npm, you may delete react and react-dom in its dependencies and use npm link to point them to your local build folder:

```js
cd your_project
yarn link ~/path_to_your_react_clone/build/packages/react
yarn link ~/path_to_your_react_clone/build/packages/react-dom
```

This seems to have two places that make me doubt.

1. The documentation states`use npm link to point ...`, but the example below use the `yarn link`. It's inconsistent.
2. IIRC, If you want to use the `yarn link`, It seems to have to run two steps, first `yarn link` (in package you want to link) and then yarn link (name). More information in [yarn link](https://yarnpkg.com/en/docs/cli/link)

**Comment by bvaughn** [comment]
`yarn` passes through most commands to `npm` (so `yarn link` is essentially the same as running `npm link`).

You are correct that running `npm link` in a project isn't sufficient unless you also run `npm link <foo>` in another project.

Would you be interested in submitting a PR to tidy this up? 😄

**Comment by monkindey** [comment]
Yes, I am glad to do it.

Could we just use the `yarn link` because I think the whole development phase of React is not need to use the npm.

How about the `yarn link` example like this ?

```js
cd ~/path_to_your_react_clone/build/packages/react
yarn link
cd ~/path_to_your_react_clone/build/packages/react
yarn link
cd your_project
yarn link react react-dom
```

I try this in my project and it works.

**Comment by bvaughn** [comment]
Great. This issue is all yours then, @monkindey! 😄 Using `yarn link` for consistency is fine, yes.

Your example looks fine too, except that I would maybe change `cd your_project` to make it more obvious that it's not a relative path (eg `cd /path/to/your/project`).

I've added an "in-progress" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by monkindey** [comment]
> except that I would maybe change cd your_project to make it more obvious that it's not a relative path 

yes, agreed.

The PR landed at https://github.com/reactjs/reactjs.org/pull/269 . Any feedback welcome.
