### ISSUE TITLE
Mixing concerns in"Extracting Components" section

### ISSUE THREAD

**Issue by danny-andrews** [reactjs/reactjs.org#2832]
In the [Extracting Components](https://reactjs.org/docs/components-and-props.html#extracting-components), an example is given of extracting an `Avatar` component:

```jsx
function Avatar(props) {
  return (
    <img className="Avatar"
      src={props.user.avatarUrl}
      alt={props.user.name}
    />

  );
}
```

This breaks the single responsibility principle, as now the `Avatar` has to know the internal structure of a user object in order to do it's work.  It seems best to keep props flat/shallow:

```jsx
function Avatar(props) {
  return (
    <img className="Avatar"
      src={props.url}
      alt={props.name}
    />

  );
}
```

By changing the `Avatar` component to take generic `url` and `name` props, you are also encouraging reuse of this component. Who knows, maybe you will want to display an `Avatar` for something other than users in the future (e.g. groups or clients).

p.s. I realize the React docs aren't primarily aimed at teaching people best-practices, but people tend to copy patterns they see given in examples, so they might as well be as solid as possible.

**Comment by alexkrolick** [comment]
🤔these are pretty debatable points. Depends on how you want to encapsulate it. You might not want to mingle top-level options like `size` and `shape` with the "data", which could have a lot of fields in order to go through some fallback logic (img => initials or generated graphic => anon user).

Another consideration is that the fields you need to choose an avatar may change over time, so passing the common User instance in directly may shield consumers from having to come up with a field mapping at each call site.

**Comment by Zeko369** [comment]
Agree with @alexkrolick on this one, there are a lot of examples where it's easier and more readable to pass the whole user object compared to passing separate values, especially with more complex components

**Comment by danny-andrews** [comment]
Hmmm...I see your point. Thanks for the feedback.
