### ISSUE TITLE
Grayscale and excessive margin top affects color-coded images and documentation

### ISSUE THREAD

**Issue by kris10cabrera** [reactjs/reactjs.org#3008]
Commit [Add a BLM banner](https://github.com/reactjs/reactjs.org/commit/5eeb4410748d0b97a1055cab66293c95dacd7d4f) applies grayscale on documentation pages, as visible on [Thinking in React](https://reactjs.org/docs/thinking-in-react.html), which makes the images unclear because the documentation references the image's colors. 

Additionally the text is cut off on the bottom because of excessive margin top.

<img width="1680" alt="Screen Shot 2020-06-01 at 5 56 25 PM" src="https://user-images.githubusercontent.com/40896596/83462633-4cf99800-a431-11ea-9312-998b567dd059.png">

<img width="1680" alt="Screen Shot 2020-06-01 at 5 56 16 PM" src="https://user-images.githubusercontent.com/40896596/83462639-5125b580-a431-11ea-8113-9de71df808a7.png">

I was able to fix the problem locally by undoing the grayscale but I do not have write access to make a PR. (The edits in `MarkdownHeader` are not causing causing issues) thanks.

**Comment by rimildeyjsr** [comment]
Came across the same issue while browsing through the Context API documentation, but this somehow seems to be localized to Chrome - this issue is not taking place in Safari or Firefox.

Screenshot from Safari:

<img width="1440" alt="Screenshot 2020-06-02 at 11 17 28 PM" src="https://user-images.githubusercontent.com/10229595/83552408-55cc9580-a527-11ea-811b-4b65e9cd3fcd.png">

Screenshot from Firefox:

<img width="1440" alt="Screenshot 2020-06-02 at 11 18 49 PM" src="https://user-images.githubusercontent.com/10229595/83552433-61b85780-a527-11ea-8c11-8fe23b06e4d8.png">

**Comment by gaearon** [comment]
Thanks for reporting.

I've fixed the blank text problem (seems to be caused by the filter affecting layout).

As for the color-coding, it is unfortunate but we're willing to temporarily leave this broken.

**Comment by hoblin** [comment]
Is there any way to switch this grayscale filter off? At least for the ppl outside of the US?

**Comment by SirJosh3917** [comment]
> As for the color-coding, it is unfortunate but we're willing to temporarily leave this broken.
This disappoints me - when reading documentation, all the syntax highlighting is gray-scale. My toolbox should not turn into Legos because of a full moon. As a developer who can see and understand the viewpoints of the BLM movement, it upsets me that it is affecting my ability to see pretty colors.

Is it possible to opt-out of this? I need my pretty colors darn-it!

**Comment by hoblin** [comment]
There is a women who was raped by two cops in Ukraine last week. Let’s switch colors to yellow-blue.

**Comment by hoblin** [comment]
> Is it possible to opt-out of this? I need my pretty colors darn-it!

You can open devtools in the browser then find the CSS rule which begins with `* {` then add `filter: none !important;` to it and that will do the trick.
