### ISSUE TITLE
Remove ReactJS From Facebook

### ISSUE THREAD

**Issue by ghost** [reactjs/reactjs.org#3077]
Dear React Team,

Mark Zuckerberg has made it abundantly clear that he is okay with Facebook being used as a tool to spread hate, misinformation, and disrupt democracy.

Facebook has allowed Donald Trump to empower White Nationalists and advocate for the National Guard to shoot citizens. It has allowed Russia to tamper with our elections and and instill autocrats across the world.

The React team recently joined an employee wide walkout advocating that Mark Zuckerberg impose sanctions on Donald Trump for his consistent false and hateful rhetoric. Facebook has repeatedly failed to meaningfully address the vast proliferation of hate on its platforms.

Zuck's most recent announcement attempts to sidestep the issue and does not do nearly enough to address the systematic spread of hate on Facebook. For example, it does nothing with regard to hateful groups using Facebook as a platform to organize and spread misinformation.

Unfortunately, the React Team's continued employment at Facebook creates an ethical dilemma for the entire React Community. Facebook is given an enormous amount of leverage within the tech industry by maintaining React.

Furthermore, many people choose to work for Facebook for the opportunity to work with your team, increasing Facebook's leverage over time.

We are calling on you to leave Facebook. All of you are extremely talented and established individuals. We are confident you will be able to find employment elsewhere. Please help us hold Facebook accountable and eliminate their position of power within our community.

Thank You,
https://dearreact.dev/

**Comment by gaearon** [comment]
Hi @dearreact,

Thank you for sharing your letter with us. As you’ve noted, the individuals on the React team disagree with some of the Facebook’s decisions and policies, including with the recent content decisions on Trump’s posts. We have definitely contemplated the possibility of leaving, and we think this is a conversation that is worth having in the broader React community.

There are a few reasons why we are not committing to leave at this moment.

Having not been vocal against Facebook’s behavior in the past, at this moment we feel obligated to spend our energy and our social capital within the company to lend our support to people pushing for changes. We understand the cynicism around this reasoning but we don't feel that we’ve exhausted our options yet, and we are seeing moderate progress. Although the recently announced changes are not nearly enough, they are also a noticeable departure from Mark's earlier position a few weeks ago. We can’t personally take credit for any of those changes. But during the first wide internal employee unrest we’ve ever seen, we think we are being more useful inside than outside. Of course, this reasoning will not stand on its own in the longer term.

Individually, our personal circumstances are not as uniform as your letter seems to suggest. Some of us can definitely leave any day with ease; for others, it will be a significant life challenge due to visa, family, health, and other issues — especially during these uncertain times. Additionally, some of us will be affected worse if other team members leave. While we respect your suggestion to take an ethical stand, this is a decision each of us has to take ourselves. We hope that you can respect this, too.

Finally, there is a question of what happens to React, and what price the community is willing to pay. This is a question your letter does not address, but we think it is an important aspect for a community of over two million people. Should we as a community abandon the React programming model? Should we abandon the React library, but start developing a fork after leaving Facebook? Should the React community pivot to that fork? Which companies would fund the work on this fork, and would they hire the team?

Are the companies that have the funds to maintain the fork morally uncompromised, or do they have contracts with ICE, support censorship in China, or radicalize teenagers? Would that still be acceptable if neither of them had complete control, and they were a part of a neutral foundation? Would Facebook be accepted into such a foundation?

If the big companies are out of question and there are not enough funds to support the whole team, who on the team will stay to work on the fork, and who will have to go? How important is having a world-scale product to experiment on to the React development, and what would React look like if it were developed without that feedback?

We’re not saying these technical questions about the project are overriding the ethical concerns for individual employees. But we think it is important to have conversations that plausibly address them, even when people disagree on the exact solutions.

We hope this provides some insight into our thinking. As current Facebook employees, we are obviously biased. We are thankful to everyone in the React community for holding us accountable and we appreciate that these questions are being asked. In the longer term, we are hoping that as a community we don't hesitate to talk about them more openly.

**Comment by dearreact** [comment]
Hi @gaearon ,

Thank you for your thoughtful and thorough response. We are a small group of people who are concerned about Facebook's track record with regards to protecting democracy. As the US election approaches, we are becoming increasingly nervous that Facebook will allow Donald Trump and his allies to to inflict even more damage across the world. 

We don't have all the answers and we don't pretend to, but we believe this conversation needs to happen. There is an existential crisis for many React developers who need to use a superb piece of technology, powered by an organization we strongly disagree with.

We would like to specifically address this comment and apologize for the harm we caused.
>  Some of us can definitely leave any day with ease; for others, it will be a significant life challenge due to visa, family, health, and other issues — especially during these uncertain times.

We did not consider some of these implications and we have amended our letter to encourage employees to seek employment elsewhere, rather than drop everything at once. We also were wrong for signing the letter "The React Community." We're just a bunch of people who care.

We do believe that Facebook employees are complicit in the crimes of Facebook and we strongly encourage you to do everything in your power to prevent Mark Zuckerberg from inflicting more damage on the world.

Thank You,
Nobodies who care
