### ISSUE TITLE
Irrelevant banner on all pages.

### ISSUE THREAD

**Issue by lLenn** [reactjs/reactjs.org#3081]
There seems to be an irrelevant banner on all pages saying: "Black Lives Matter. Support the Equal Justice Initiative."
I don't see what the political climate has to do with React and would not expect to see political slogans on here.

**Comment by rickhanlonii** [comment]
Black Lives Matter is not a political statement. It's a human rights statement.

**Comment by lLenn** [comment]
The BBC, as a neutral network, has designated it a political movement. If you want to discuss the legitimacy of "Black Lives Matter" and throw studies around I'm happy to do so on another forum. The fact remains that it's irrelevant to React.

**Comment by msoopern** [comment]
It's also really annoying bc the navbar is sticky and takes up valuable screen space. Can we have a way to close it like on https://angular.io?

**Comment by lLenn** [comment]
> 
> 
> Black Lives Matter is not a political statement. It's a human rights statement.

Why stop at "Black Lives Matter" then? I also have something that you can add: Free Hong Kong. As we all know, China's not a free country and has an oppressive regime which makes it a human rights statement. It's not inclusive if you don't have my statement there aswell.

**Comment by gaearon** [comment]
I think it’s a legitimate question why the banner is scoped to a US-based movement. The answer is that although our audience is international, the React core team is primarily based in US. I think it would make total sense for a project primarily developed in Hong Kong to include a statement supporting human rights there.

As for why it’s up at all, it’s because we’ve made a decision as a team to put the banner up. We can respect that not all projects would choose this stance, and we appreciate your feedback on this. However, we hope that you can respect our decision even if you disagree.

I don’t think debating it would prove illuminating to either you or us — so I’m going to lock this issue. Please remember that trolling, bating, and other attention-stealing behavior will not be tolerated in this repository.

Thank you.
