### ISSUE TITLE
Profiler > Component render count is missing

### ISSUE THREAD

**Issue by mtrabelsi** [reactjs/reactjs.org#3246]
Hi,

According to the [Documentation](https://reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html), from the Flame chart I can either "double click" on one of the ranked bars to see particular component with its props/state and his number of count (component view).

But this option seems to be not existing, or is it old documentation?
I'm happy to write a PR, but a brief explanation is needed here! thanks!

Best regards

**Comment by eps1lon** [comment]
I can only find a mention of "double click" under [component chart](https://reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html#component-chart) which no longer exists.

**Comment by pjchender** [comment]
I think the documentation has not been updated. This feature has been removed because of performance issues. You could check the blog post here - [https://reactjs.org/blog/2019/08/15/new-react-devtools.html](https://reactjs.org/blog/2019/08/15/new-react-devtools.html), and related [#17960](https://github.com/facebook/react/issues/17960)
