### ISSUE TITLE
Why the console.time run twice in useState

### ISSUE THREAD

**Issue by yuki070** [reactjs/reactjs.org#3510]
I want to do some expensive computations in the `useState`. So I use a function for the `useState` 's param.

When I use `console.time` to track the time cost, I find an unusual result.

This is the [code link](https://codesandbox.io/s/console-time-in-usestate-5uvuw). It's simply as below:

```js
import { useState, useEffect } from "react";

export default function App() {
  const [num, setNum] = useState(() => {
    console.time("initState");
    const now = new Date();
    while (new Date().getTime() - now.getTime() < 2000) {
      //
    }
    console.timeEnd("initState");
    return 100;
  });

  console.time("render");

  useEffect(() => {
    console.timeEnd("render");
  }, []);

  return <div>num is {num}</div>;
}

// output
// initState: 0.10000006295740604ms 
// initState: 0.034999800845980644ms 
// render: 1.2649998534470797ms 
```

I can see the `console.time` print twice in the console. And the output of `console.time` seems not corrent.

It that any magic in useState ?

**Comment by eps1lon** [comment]
> It that any magic in useState ?

It is probably caused by your app being inside `React.StrictModet`. This will cause functions passed to `useState` being called twice to detect unexpected side-effects. An exhaustive list of these instances of "double-invocation" can be found in https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects.

React 17 will block console methods in the second call though so you might want to try to upgrade.
