### ISSUE TITLE
Need confirmation if the following syntax is correct or not

### ISSUE THREAD

**Issue by hyfydistro** [reactjs/reactjs.org#3535]
[React - Docs - Main Concepts - 8. Lists and Keys - Keys Must Only Be Unique Among Siblings](https://reactjs.org/docs/lists-and-keys.html#keys-must-only-be-unique-among-siblings)

Need confirmation if the following syntax is correct or not, because I'm not sure what `props.id `is referring to in the image (code) displayed:

![Screenshot_2](https://user-images.githubusercontent.com/24542308/108499455-e24efc00-72e0-11eb-86fa-5cc5d24ee7c0.png)
.

Also where would `props.key `would be?

**Comment by rickhanlonii** [comment]
Yes, the syntax is correct. The text is referring to what the Post component can internally access. It's saying that inside of the post component, you can access the `id` passed to it as `props.id`, but you cannot access the `key` passed to it as `props.key`, because that's used by React and not passed down. For example:

```js
function Post(props) {
  // This is defined
  console.log(props.id);
  
  // This is undefined
  console.log(props.key);
}
```
