### ISSUE TITLE
Ajax calls inside React components

### ISSUE THREAD

**Issue by Myrga** [reactjs/reactjs.org#3572]
Hello! :)

I stumbled upon [this documentation](https://github.com/reactjs/reactjs.org/blob/master/content/docs/faq-ajax.md) explaining how to make ajax calls inside React components and I don't understand this comment:
```javascript
// Note: it's important to handle errors here
// instead of a catch() block so that we don't swallow
// exceptions from actual bugs in components.
```

In my understanding of promises, having a catch as a callback or as a chain won't change how "much" of the code is catched. 
I don't understand, here, how using a `.catch()` would swallow exceptions from actual bugs in the component if the catch in only applied on the fetch. 
Can someone explain the difference?

Thank you 😊

**Comment by rickhanlonii** [comment]
Hey @Myrga, sorry this isn't explained very well!

This has to do with the differences between:

```js
fetch("https://api.example.com/items").then(
  result => {
    // [1] An error here does not get caught below
    setState("success");
  },
  error => {
    setState("failure");
  }
);
```

and

```js
fetch("https://api.example.com/items")
  .then(result => {
    // [1] An error here DOES get caught below
    setState("success");
  })
  .catch(error => {
    setState("failure");
  });
```

The first version will not call the error callback if the setState in [1] errors. The second version _will_ call the error callback in the catch block if the setState in [1] throws. It's important to handle errors using the first version, instead of a catch() block like in the second version so that we don't swallow exceptions from actual bugs in components.

**Comment by rickhanlonii** [comment]
Going to close this as answered, but let me know if you have any questions!
