### ISSUE TITLE
Typo in the docs

### ISSUE THREAD

**Issue by AnandBIT** [reactjs/reactjs.org#3582]
Doc Link - (https://github.com/reactjs/reactjs.org/blob/master/content/docs/components-and-props.md)
In the note section of (https://reactjs.org/docs/components-and-props.html#rendering-a-component), there written   
........but <Welcome /> represents a component and requires Welcome to <ins>be in scope</ins>.  
The last words need to be changed like that :-  
..........but <Welcome /> represents a component and requires Welcome to <ins>start with an uppercase letter</ins>.

**Comment by elchininet** [comment]
@AnandBIT, I think that it is not a typo, what the documentation says is:

* If you write `<welcome />`, React will not make anything with this element (it will treat it as an HTML element)
* If you write `<Welcome />` React will compile it to `React.createElement(Welcome, null);`, therefore it requires `Welcome` to be in scope (otherwise it will throw an error)

**Comment by AnandBIT** [comment]
Ok, thanks for the explanation
