### ISSUE TITLE
Crashes when navigating between top-level menu items

### ISSUE THREAD

**Issue by gaearon** [reactjs/reactjs.org#365]
I get crashes when navigating between top level Blog and Community items and back. Sometimes it blows away the whole page.

<img width="654" alt="screen shot 2017-11-29 at 00 11 51" src="https://user-images.githubusercontent.com/810438/33351114-1ab79efa-d49a-11e7-8dfa-3d19a29b9799.png">
<img width="642" alt="screen shot 2017-11-29 at 00 12 14" src="https://user-images.githubusercontent.com/810438/33351115-1ad1e2e2-d49a-11e7-9dfd-026882615db0.png">
<img width="317" alt="screen shot 2017-11-29 at 00 12 19" src="https://user-images.githubusercontent.com/810438/33351116-1aee3302-d49a-11e7-85f8-7f18baeb6cad.png">
<img width="574" alt="screen shot 2017-11-29 at 00 13 53" src="https://user-images.githubusercontent.com/810438/33351135-35972970-d49a-11e7-93a8-97078f506c7c.png">

To repro:

1. Open https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html
2. Press "Community" on the top level
3. Page is blown away
4. Refresh
5. Press "Blog"
6. Page isn't blown away, but there are errors

**Comment by alexkrolick** [comment]
Possibly related to https://github.com/reactjs/reactjs.org/issues/298

**Comment by gaearon** [comment]
Paging @KyleAMathews

**Comment by KyleAMathews** [comment]
I wasn't able to reproduce — I can look later at how `eventHandler` could be called before `window.___history` is set.

**Comment by gaearon** [comment]
Doesn't repro for me either now 😞

**Comment by bvaughn** [comment]
I _have_ seen Gatsby occasionally get into a broken state- maybe not quite like this- and refreshing the page always fixes it, which makes it difficult to track down.

One reliable way to get it broken like this is to load a page without the file extension. For example, rather than loading [reactjs.org/docs/hello-world.html](https://reactjs.org/docs/hello-world.html), open [reactjs.org/docs/hello-world](https://reactjs.org/docs/hello-world). Now every link you click causes the error @gaearon mentioned above:
> app-ac5cc93e27d86a811a05.js:1 Uncaught TypeError: Cannot read property 'push' of undefined

I think I may have chatted with @KyleAMathews about this before, but I'm not certain.

**Comment by bvaughn** [comment]
I _may_ have fixed this issue via PR #397 but since I was unable to reproduce it I don't know.

I do still see some errors in the console:
![screen shot 2017-12-04 at 12 52 26 pm](https://user-images.githubusercontent.com/29597/33575608-0a12dd92-d8f2-11e7-9b9a-9566cff6934f.png)

But no crashing.

**Comment by bvaughn** [comment]
I'm going to assume this issue has been fixed for now given that the repro steps are not sufficient to repro it. Let's re-open if we're still seeing it.

**Comment by gaearon** [comment]
Nice, thanks Brian!
