### ISSUE TITLE
Docs > Getting Started > single-file-example broken link

### ISSUE THREAD

**Issue by Genizzz** [reactjs/reactjs.org#3758]
At 
* Docs
* * Getting Started [https://reactjs.org/docs/getting-started.html](https://reactjs.org/docs/getting-started.html)
* * * Try React
* * * * Online Playgrounds

In the block 
`If you prefer to use your own text editor, you can also download this HTML file single-file-example ...`

The `single-file-example` leads to 
[https://raw.githubusercontent.com/reactjs/reactjs.org/main/static/html/single-file-example.html](https://raw.githubusercontent.com/reactjs/reactjs.org/main/static/html/single-file-example.html)
Which returns a 404 error.

**Comment by rohildshah** [comment]
The same broken link is also present in [the next tutorial](https://raw.githubusercontent.com/reactjs/reactjs.org/main/static/html/single-file-example.html) under the `Quickly Try JSX` subheading with raw text `... an example HTML file with JSX ...`. It's likely the broken link is also present in other tutorial pages although I've not checked.

I did some searching and it seems the issue is an incorrect branch name. The `main` in the link should be switched with `master`. The updated link would be: [raw.githubusercontent.com/reactjs/reactjs.org/master/static/html/single-file-example.html](raw.githubusercontent.com/reactjs/reactjs.org/master/static/html/single-file-example.html).

**Comment by Genizzz** [comment]
@rohildshah thank you for the check. I see the original link works now. Both `main` and `master` are available now.
