### ISSUE TITLE
Broken top navigation links at 404 page

### ISSUE THREAD

**Issue by andreysdr** [reactjs/reactjs.org#393]
1. Go to non existing page, for example - https://reactjs.org/component-api.md (I get it from react native docs "React.Component API" https://facebook.github.io/react-native/docs/state.html)
2. Click on any top navigation link "Docs", "Tutorial", etc. 

Errors in console 
![8929431080](https://user-images.githubusercontent.com/16011911/33545141-41a9e0a6-d8ee-11e7-8eb7-893d34205364.png)

Tried in latest chrome and safari.

**Comment by gaearon** [comment]
Looks related to https://github.com/reactjs/reactjs.org/issues/365.
cc @KyleAMathews

**Comment by bvaughn** [comment]
Yeah, sounds like the same thing I'm describing in [this comment](https://github.com/reactjs/reactjs.org/issues/365#issuecomment-347738015). ☹️ 

Thanks for reporting. We'll try to dig into this soon.

**Comment by bvaughn** [comment]
Unfortunately this can't be repro'd in dev mode because Gatsby handles 404s very different in dev vs prod. Shortest path to repro locally is `yarn build && serve ./public`.

The error is from [trying to push to `window.___history` which doesn't exist](https://github.com/gatsbyjs/gatsby/blob/e104f5a98120563eb9c0d83dc2cabf229d9f1877/packages/gatsby/cache-dir/production-app.js#L72).

My current _guess_ is that Gatsby isn't properly executing [this code](https://github.com/gatsbyjs/gatsby/blob/e104f5a98120563eb9c0d83dc2cabf229d9f1877/packages/gatsby/cache-dir/production-app.js#L104-L106) which sets `window.___history = history` in the event of a 404.

**Comment by bvaughn** [comment]
Just as a proof-of-concept, I added a line [to this short-circuit](https://github.com/gatsbyjs/gatsby/blob/e104f5a98120563eb9c0d83dc2cabf229d9f1877/packages/gatsby/cache-dir/loader.js#L258-L261) that sets a stub `window.___history` object:
```js
window.___history = history = {};
```
This seems to unbreak navigation links.

**Comment by bvaughn** [comment]
Just as a proof-of-concept, I added a line [to this short-circuit](https://github.com/gatsbyjs/gatsby/blob/e104f5a98120563eb9c0d83dc2cabf229d9f1877/packages/gatsby/cache-dir/loader.js#L258-L261) that sets a stub `window.___history` object:
```js
if (!page) {
  console.log(`A page wasn't found for "${path}"`)
  window.___history = []; // TEST
  return
}
```
This prevents the undefined runtime error (but doesn't "fix" things since this isn't the react-router history object).

**Comment by bvaughn** [comment]
It's interesting to note that this defect doesn't seem to impact the Gatsby site.

**Comment by KyleAMathews** [comment]
Sorry for not being able to jump on this :-( in a gazillion meetings today but I'll get on this tonight and look into why it could be undefined.

**Comment by bvaughn** [comment]
No problem Kyle. I started digging into it before I realized that it wasn't happening on the Gatsby site, at which point I updated all of the Gatsby plugins and now it doesn't happen on the React site either. 😄 

We could bisect to find out when it was fixed, if it's important to know.

**Comment by KyleAMathews** [comment]
@ataylorme reported this on a site he's building where it's happening on every initial page load — with that I was able to dive into the issue and make this PR https://github.com/gatsbyjs/gatsby/pull/3313

It's out in the latest gatsby release.

**Comment by bvaughn** [comment]
🎉 Nice!
