### ISSUE TITLE
Official React Conf seems unindexed by Google

### ISSUE THREAD

**Issue by gaearon** [reactjs/reactjs.org#410]
When I search for "react conf" I can't find [our own conf](http://conf.reactjs.org/) on the first page.
Could it be because it's built with CRA and isn't server rendered and/or missing a polyfill?

In any case worth investigating what the crawler sees.

**Comment by raisedadead** [comment]
Hi @gaearon 

There is an excellent tool https://support.google.com/webmasters/answer/6066468?hl=en that we could use, (I have used this frequently, on some of my projects that have CRA)

Unfortunately, I will not be able to run the test myself because there is a verification step on property ownership (which is the `reactjs.org` domain/subdomains, etc.).

Other than that its a really good tool.

It even has a section that gives you the exact headers that the crawler got, plus you can request indexing from there.

We might be missing adding some of the structured data to the markup to improve the SEO and rank higher, and correctly as the first result. 

Hope this helps in debugging.

**Comment by ishankbahl** [comment]
Could it be because the site isn't using https/http ?

**Comment by tylercaldwell** [comment]
The page appears to be serving a 404 (but still renders the content as though a 200 were served). Not sure if this was the case when the issue was opened, but if most search engine crawlers are served a 404 they will not index the page.

**Comment by saranshkataria** [comment]
I see the first link pointing to react conf. This issue can be closed I guess?

**Comment by jitinmaher** [comment]
Hey @gaearon , can you confirm if this issue still persists? 
We can confirm that the the link you posted in your comment was correct and well served as the first result when google searched.

![reactconfindexing](https://user-images.githubusercontent.com/7746087/49811450-4f71b900-fd89-11e8-84c2-8d17ea8718ce.gif)

**Comment by saranshkataria** [comment]
Closing this out since it seems to be resolved.
