### ISSUE TITLE
[Beta] Make Deep Dives linkable

### ISSUE THREAD

**Issue by gaearon** [reactjs/reactjs.org#4298]
Currently Deep Dives don't have link anchors. We should make them work the same way as headers, and make them anchors.

**Comment by amareshsm** [comment]
I checked on this. Since deep dive is a JSX component we have a find a way to generate Ids to make them as anchors. The fix-headings (generateHeadingIDs.js) script generates ids only for MDX heading elements. 

Either we need to modify the generateHeadingIDs.js and validateHeadingIDs to make them work for <DeepDive> JSX tags also. In this case, we can use the deep dive component title as id.

Eg: <DeepDive title="How to manage a list of refs using a ref callback"  _id="how-to-manage-a -list-of-refs-using-a-ref-callback"_ >  

Or need to move the deep dive element to the MDX file.

@gaearon  I would like to know your thoughts on this.

**Comment by ashutosh887** [comment]
Should I work on this Issue @gaearon

**Comment by ibarapascal** [comment]
The link is added, and the related merge could be found within this issue: https://github.com/reactjs/reactjs.org/issues/5304
