### ISSUE TITLE
Warnings when running `yarn dev`

### ISSUE THREAD

**Issue by gaearon** [reactjs/reactjs.org#432]
Not sure what they mean but they seemed odd to me.
```
⠂ source and transform nodesWarning: No slug found for "home/examples/a-component-using-external-plugins.md". Falling back to default "/home/examples/a-component-using-external-plugins.html".
Warning: No slug found for "home/examples/a-simple-component.md". Falling back to default "/home/examples/a-simple-component.html".
Warning: No slug found for "home/examples/a-stateful-component.md". Falling back to default "/home/examples/a-stateful-component.html".
Warning: No slug found for "home/examples/an-application.md". Falling back to default "/home/examples/an-application.html".
Warning: No slug found for "home/marketing/component-based.md". Falling back to default "/home/marketing/component-based.html".
Warning: No slug found for "home/marketing/declarative.md". Falling back to default "/home/marketing/declarative.html".
Warning: No slug found for "home/marketing/learn-once-write-anywhere.md". Falling back to default "/home/marketing/learn-once-write-anywhere.html".
```

**Comment by bvaughn** [comment]
Ah, yes. This warning means that there are markdown files in the [`content` folder](https://github.com/reactjs/reactjs.org/tree/master/content) that have no associated [`template](https://github.com/reactjs/reactjs.org/tree/master/src/templates). This is probably not common for a Gatsby app, but in our case it's because we split the homepage up from what used to be the a single markdown file into multiple ones, pieced together by a ["page"](https://github.com/reactjs/reactjs.org/blob/master/src/pages/index.js) because of the unique layout constraints. (We left the text in the `content` folder though so it could be easily translated via the Crowdin effort.) I left a comment about it [inline](https://github.com/reactjs/reactjs.org/blob/4aaaa509c0d8f043b9f975cda74e5693024b8ebd/gatsby/onCreateNode.js#L50-L55) but I realize that's not super discoverable.

Anyway, just a bit of backstory. I should probably just remove the warning since it probably causes more confusion than it helps. :smile:

**Comment by bvaughn** [comment]
Removed this unhelpful log via 27293d63b
