### ISSUE TITLE
🌶️ rubbish

### ISSUE THREAD

**Issue by lgn618** [reactjs/reactjs.org#4433]
why do your team support ukraine  without any knowing of their history ?because of the us government ?   dog thing,  cao n m,si quan jia de dog thing ,terrible

**Comment by towry** [comment]
Stand for world peace.

Please make sure to support any people suffering in the war no matter what color is in the future.

**Comment by jack9603301** [comment]
Although it is not known whether the source is authentic, Ukraine also has a great deal of responsibility in the events at this time. They don't understand politics. . I don't want to judge too much, please don't politicize open source. Technologists are basically not good at politics, and they shouldn't interfere too much in politics.

**Comment by hmmhmmhm** [comment]
Helping civilians in the Ukrainian War is not a political issue.

Supporting Ukraine is an act of demanding peace itself. Fundraising to help civilians in danger cannot be seen as any political act. Most of the actions to help Ukraine are against civilians, meaning to stop attacking innocent people. Everyone has witnessed innocent people in Ukraine being attacked, and not many people deny it.

Developers and several open-source organizations do not live in virtual spaces far from reality, and the reality we live in sees many attacks on Ukrainian civilians. If this is called politics, all social movements are considered political, but most modern societies do not object to human rights-related support.

<br/>

**Github Chief Executive Officer - Thomas Dohmke**
>"What we are witnessing now is something I never wanted to see again. It is devastating for the innocent people in Ukraine, and it is leading to feelings of helplessness and anger for those of us near and far away."
https://github.blog/2022-03-02-our-response-to-the-war-in-ukraine

**Hashicorp**
> "We’re sorry, but because of the conflict underway in Ukraine, HashiCorp is prohibiting availability of our products and services in Russia and Belarus."
https://discuss.hashicorp.com/t/access-to-releases-hashicorp-com-is-denied/36348

<br/>

Keep in mind that the technology of the advanced IT industry operating in the United States cannot be supported in countries that act of war crimes. React has never been included in the scope of U.S. export suspension, but Facebook and GitHub, U.S. companies, have minimal actions to follow as members of society. It should keep in mind that they are making this technology available to everyone with minimal social behavior, and that many teams are moving according to their social position.

Simply opening a link to charity fundraising for Ukraine is not a political act. If this was the time for the United States to take real political action, it would not be possible to even use it at all in russia, not just a simple charity fundraising event for Ukraine. Don't think humanitarian behavior has political significance. Deepening these disputes can serve as an excuse for blocking access to open source sites in the face of sanctions.

If you don't actually want this, here's what you should do.
1. Don't create disputes or spams that can intensify public opinion.
2. Send PR to emphasize that this is support for civilians so that political opinions are not contained.
3. Persuade them in appealing English. (Don't blame others emotionally.)

"Real political action" is increasingly required while you send issues to innocent react.js teams.

Don't fight the political messages of the non-existent react.js team, see what the existential threat is, and the political messages required of the existential OSS below. While many people are arguing with the react.js issue page, these threats are becoming real, and you should know that the react.js team is not part of it.

<br/>

**An open letter from IT industry specialists to protect Ukraine from information warfare.**
>"On February 24, 2022, the Russian Federation cowardly attacked independent Ukraine. They are waging a dirty information war against the whole world and direct armed warfare on the territory of Ukraine.
>
>The publicly available IT projects, package managers, forums, CDNs, and other resources created for the benefit and convenience of IT professionals are now used to wage war and destroy innocent civilians. We also believe that these resources (i.e. source code, software, and other digital information) help disseminate false information in Russia and can be used to conduct military operations. These resources also make it possible to finance and continue the war in Ukraine with the help of the Russian IT sector.
>
>We call you to stop helping the Russian IT sector in any activity. We call you to stop using Russian information resources and not finance the Russian IT sector, because this way you finance the war. We call to the public resources providers used by the Russian IT sector to restrict any traffic and access to these networks from Russia:"
https://github.com/stop-war-in-ukraine/stop-russia-it

**Avi Press - Founder of Scarf**
> “Scarf will be blocking all package and container downloads originating from Russian Government sources until further notice.”
>
>"My analysis showed that Scarf has fulfilled ongoing software download requests from at least 17 distinct sources that have been confirmed to originate from the Russian Government. This activity primarily comprises their downloading of containerized applications via Scarf Gateway, including internal communications & chat, IT service orchestration, and more. The traffic spans multiple government departments, including The Federal Guard Service, The Ministry of Finance, The Main Center of Information and Computing, Ministry of Culture, and others. 
>
>Today, open-source software powers just about everything we touch. I’m constantly reminded of that as I work day-in and day-out building Scarf. That still doesn’t make it any less heartbreaking to see beautiful open technology being exploited by forces like the Russian government so they can more effectively invade Ukraine. It then begs the question of how else they might be leveraging OSS, today, and in the future. With the looming threat of Russian Intelligence organizations resorting to cyber attacks to get their way, it’s hard to imagine OSS not playing a key role.
>
>The notion of Russian government cyber attack operations leveraging software downloaded through Scarf’s platform is unacceptable. The notion of facilitating the atrocious invasion we're witnessing in Ukraine is not acceptable. As a result, Scarf will be blocking all package and container downloads originating from Russian Government sources until further notice. Traffic originating from other Russian sources such as businesses, civilian internet service providers, or otherwise, will be unaffected by this change. "
https://about.scarf.sh/post/standing-with-ukraine?utm_source=thenewstack&utm_medium=website&utm_campaign=platform

**Comment by jack9603301** [comment]
Okay, but still to say we can't judge world events and technologists shouldn't stand for anything involving national events, the open source community can support peace, but it has to be neutral, especially if the details aren't clear, It is a wrong decision to choose to stand blindly for this event. It is certain that if this event is true, reactjs has made a wrong decision, and open source should not be politicized.

**Comment by hmmhmmhm** [comment]
@jack9603301
Humanitarian aids is not political.
There can be no neutrality when it comes to human rights.
Are all organizations that provide humanitarian aid political organizations?
It is a remark without a basic concept of human rights.

**Comment by jack9603301** [comment]
Even just in terms of human rights, this is not an issue that a technical open source group should be involved in, because it's not just a matter of donations. The tech community shouldn't speak too much about such events

**Comment by hmmhmmhm** [comment]
> The tech community shouldn't speak too much about such events

Tell us clearly what you're concerned about, it's not clear what you're against.
You said that what is not a political issue is a political reason, but now you tell them not to post the issue at all.

**Comment by hmmhmmhm** [comment]
@jack9603301 
经过长时间的讨论，在经过多数同意后，以中立的信息修改了react主页上的文章。 希望把政治上可能被误解的信息改善为更好的善意信息，并帮助制定所有人都需要的解决方案。https://github.com/reactjs/reactjs.org/pull/4438

让我们创造一个更好的 React.js，让社区朝着更好的方向发展。

**Comment by gaearon** [comment]
I posted this response in one of the other threads, but I can't find it so I'll repost it here:

---

Hi there.

People in Ukraine are in the middle of a severe humanitarian crisis. According to UN, a million of people have become refugees this week. It is widely reported that many people, including kids, are sheltering in basements, traveling in freezing temperatures, and are short on supplies. This is why we would like to encourage everyone using React to help those in need.

It is true that we have not responded to every humanitarian disaster. There is no single objective threshold of scale, and we’ve only started doing these banners recently. However, this is not a zero-sum activity. First, we are only a single project, and there are other projects which may choose different causes (or not support any causes at all). Second, getting the message out about one crisis does not hurt people affected by a different crisis. This is why the “whataboutism” is mostly a distraction, and we will not spend time seriously entertaining it.

The Meta Open Source teams have collectively taken a stance in supporting humanitarian aid to Ukraine. The React team supports this stance. You are free to suggest other causes to support in the future. However, spamming the repo with duplicate issues and comments is disruptive. This violates the GitHub the terms of service, and GitHub will be removing this type of content. There is nothing more we would like to say on this at this point, so we will be locking this issue.

Thank you!
