### ISSUE TITLE
Avoid redundant state should cover heavy calculations

### ISSUE THREAD

**Issue by cgarrovillo** [reactjs/reactjs.org#4664]
https://beta.reactjs.org/learn/choosing-the-state-structure#avoid-redundant-state

The principle is great for covering a very common anti-pattern in React codebases, but I think the example shown is too simple in the sense that this is only dealing with primitives.  

It could be easy to confuse that heavy calculations such as states involving Arrays should follow this principle too,  whereas those are better put into their own local state through the use of a `useEffect` instead of following this principle

ie. 
```tsx
import { useState, useEffect } from 'react';

export default function Child({ 2DArray = [] }) {
 const [1DArray, set1DArray] = useState([]) 

 useEffect(() => {
    const flattened = 2DArray.flat()
    set1DArray(flattened)
}, [2DArray] )

return ( ...
```

**Comment by eps1lon** [comment]
> whereas those are better put into their own local state through the use of a useEffect instead of following this principle

They're not better off being put into separate state because now you split your rendering across two commits. One will contain and updated 1DArray but outdated 2DArray. Only the second commit will contain a consistent screen where both 1DArray and 2DArray are up-to-date. 

This derived state should be computed during render not in a effect. If that computation is heavy, `useMemo` is the proper hook to reach for here:

```jsx
export default function Child({ 2DArray = [] }) {
 const 1DArray = useMemo(() => {
    return 2DArray.flat()
  }, [2DArray] )
  return ( ...
```

Or, if 2DArray can be rendered with a lower priority you can [`useDeferredValue`](https://reactjs.org/docs/hooks-reference.html#usedeferredvalue)
```jsx
export default function Child({ 2DArray = [] }) {
 const deferred2DArray = useDeferredValue(2DArray)
 const 1DArray = useMemo(() => {
    return deferred2DArray.flat()
  }, [deferred2DArray] )
  return ( ...
```

**Comment by cgarrovillo** [comment]
Wow yeah thats right that is much cleaner to read and understand..

So with that,  do you think this is still helpful info to add onto that page?

**Comment by eps1lon** [comment]
New beta docs will cover these use cases.
