### ISSUE TITLE
The expected error provided in the docs does not match up with the error that actually occurs in the live code editor.

### ISSUE THREAD

**Issue by rahulrao0209** [reactjs/reactjs.org#4733]
The expected error mentioned in the docs for the _**forwarding refs section(Accessing another component's DOM nodes)**_ does not match up with the actual one in the live code editor.

**Expected Warning/Error as per the docs**
```
Warning: Function components cannot be given refs. 
Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
```

**Actual Exception being shown in the live code editor**
```
Runtime Exception
App.js: Cannot read properties of null (reading 'focus') (11:21)

   8 |   const inputRef = useRef(null);
   9 | 
  10 |   function handleClick() {
> 11 |     inputRef.current.focus();
                            ^
  12 |   }
  13 | 
  14 |   return (
```

Linking the docs issue location for quick reference. Hope this helps.
[Accessing another component's DOM nodes](https://beta.reactjs.org/learn/manipulating-the-dom-with-refs#accessing-another-components-dom-nodes)

**Comment by gaearon** [comment]
The error in question is printed in the _console_ (before you try to click the button).

We'll need to implement console output in the sandbox so that you don't have to open the browser DevTools, but the error is visible there.

<img width="675" alt="Screenshot 2022-06-10 at 15 47 26" src="https://user-images.githubusercontent.com/810438/173091372-dbe72048-356c-4457-8cde-f47fcd4e00e7.png">

**Comment by rahulrao0209** [comment]
Okay, thanks Dan!
