### ISSUE TITLE
console messages are appearing twice

### ISSUE THREAD

**Issue by harish-sethuraman** [reactjs/reactjs.org#4783]
Seems like console messages are appearing twice in the console 

https://user-images.githubusercontent.com/32865581/176702694-cae6474e-b9e8-4bac-b793-2b06ea68987d.mov

**Comment by Lalman888** [comment]
@harish-sethuraman  You are running your app in strict mode. Go to index.js and comment strict mode tag. You will find a single render.
This happens is an intentional feature of the React.StrictMode. It only happens in development mode and should help to find accidental side effects in the render phase.

**Comment by harish-sethuraman** [comment]
Thanks 😅 Yea I knew that console messages are rendered twice in strict mode. But when I implemented the sandpack consoles I remember they appeared only once 🙈 https://github.com/reactjs/reactjs.org/pull/4672#issuecomment-1142410041 . Just wanted to confirm if anyone else noticed the change in behaviour. Or may be (it never appeared once?) it was me who got it wrong 😅
