### ISSUE TITLE
Mobile layout scrolls horizontally

### ISSUE THREAD

**Issue by bvaughn** [reactjs/reactjs.org#56]
This shouldn't happen 😄 

![mobile-layout-hor-scorll-bug](https://user-images.githubusercontent.com/29597/31309857-0c56905e-ab42-11e7-8385-55c7e32717b1.gif)

**Comment by yangshun** [comment]
Weird, I'm unable to reproduce this. Opened https://reactjs.org/docs/hello-world.html on Chrome Devtools with iPhone 5.

**Comment by fpoumian** [comment]
I'm also unable to reproduce this in either Chrome Devtools or in an actual Samsung Galaxy S6

**Comment by thomasyimgit** [comment]
Cannot reproduce it either

**Comment by bvaughn** [comment]
I'm able to reproduce it in Chrome with mobile layout. (Chrome in desktop mode will not resize narrow enough to reproduce it but if you toggle it to iPhone size, it repros.)

**Comment by thomasyimgit** [comment]
@bvaughn Oh I got it. I'll work on it right now

**Comment by thomasyimgit** [comment]
It's so weird that I can reproduce on production but not in my local environment, with this width: 509px.

**Comment by bvaughn** [comment]
Great! This issue is all yours, @thomasyimgit 😄

I've added an "in-progress" label so that others will know not to start work on the issue. If you change your mind about the issue, no worries! Just let me know so that I can remove the label and free it up for someone else to claim.

Cheers!

**Comment by thomasyimgit** [comment]
@bvaughn Hi Brian, sorry about the duplicated PR earlier. Just need to get myself familiar with how things work here. :)

About this issue, I saw this bug like two or three times but still cannot reproduce it 100%. I tested in every mobile sizes and in Chrome incognito mode, and it works fine. So it's kind of hard to know my solution is REALLY solving the problem. So I can only provide somethings I've noticed that may cause this problem:

1. the `<body>` is missing a `max-width: 100%;`
2. the attributes of the viewport meta tag is not that complete. It misses: `maximum-scale=1, minimum-scale=1`

Sorry about that.

**Comment by bvaughn** [comment]
I've also had some trouble reproducing it 100% of the time.

> the attributes of the viewport meta tag is not that complete. It misses: `maximum-scale=1, minimum-scale=1`. So when you zoom even a little bit, it enables the horizontal scroll.

I believe this is intentional, as per the UI designer who helped create the new site. cc @joecritch for confirmation.

**Comment by joecritch** [comment]
Yeah, ideally we don't want to have `maximum-scale=1, minimum-scale=1` because that disables zooming, which is an accessibility problem.

I've not looked into this particular issue, but I had a similar issue with inline `<code>`, whereby it needed ` word-wrap: break-word` to prevent horizontal scrolling on pages which had long  `<code>` "words".

If it's not an issue on other pages, perhaps see if it's some particular content which is causing the issue?

**Comment by bvaughn** [comment]
> If it's not an issue on other pages, perhaps see if it's some particular content which is causing the issue?

For me, when I'm able to reproduce it, I can reproduce it on every page.

**Comment by thomasyimgit** [comment]
Are we still following up this issue? I'm kind of stuck now;(

**Comment by bvaughn** [comment]
No worries. I'll remove the "in-progress" label if you're stuck. Maybe someone else will have an idea we haven't thought of yet. 😄

**Comment by SadPandaBear** [comment]
I figured out that removing those **margin-left: auto** and **margin-right: auto** from header would fix the problem on most pages.

![screenshot_1](https://user-images.githubusercontent.com/13281562/31556307-c97a88fc-b01a-11e7-997e-0144c5cadbc9.png)

Perharps I can open a PR when i get this to work.

**Comment by bvaughn** [comment]
cc @joecritch in case he knows of anything that might break as a result of removing those 😁

**Comment by SadPandaBear** [comment]
Well, removing some **margin: auto**'s did the job to me for most pages, but I don't believe removing these rules is what's supposed to be doing on this issue.

I believe this is a **Chrome DevTools Issue** related to zooming in/out from Desktop to Device view mode since that's the only way I could reproduce it (Couldn't reproduce it on my phone though.

**Plus, I want to show this:**

_Non horizontal scrollable layout:_
![screenshot_1](https://user-images.githubusercontent.com/13281562/31564548-9e0f5c8c-b039-11e7-966f-51883e316a1d.png)

_Horizonal scrollable layout_
![screenshot_2](https://user-images.githubusercontent.com/13281562/31564549-9e33868e-b039-11e7-9f14-fd597f909e1b.png)

Maybe @joecritch knows something about these Chrome DevTools tricks?

**Comment by bvaughn** [comment]
> I believe this is a Chrome DevTools Issue related to zooming in/out from Desktop to Device view mode since that's the only way I could reproduce it (Couldn't reproduce on my phone though).

I also now believe this was the cause.

**Comment by SadPandaBear** [comment]
Not 100% sure, but I think this if this is the real cause, then google/WebFundamentals#2984 can tell us something (couldn't find the related issue in bugs.chromium yet).

**Comment by el1f** [comment]
Can't reproduce on any of these devices:
- iPhone 6 running iOS 11.0.3 on Safari
- Oneplus Two running Android 7 Nougat on Chrome
- Chrome DevTools

Is this still relevant or is it just that I'm unable to reproduce it?

**Comment by bvaughn** [comment]
I think it's safe to close this issue given the zoom comments above and the general difficult reproducing it. 👍 Thanks all!
