### ISSUE TITLE
Test Utils page is available in Google search results, but the front-end redirects the visitor

### ISSUE THREAD

**Issue by halfzebra** [reactjs/reactjs.org#605]
## Note from maintainers: If you'd like to work on this issue, please comment to claim it so we don't have duplication of work – thanks!

It seems like there's a problem with routing on https://reactjs.org/docs/test-utils

I'm getting redirected to Page Not Found by the router on the front-end.

`curl https://reactjs.org/docs/test-utils` returns the expected document.

It's accessible via https://reactjs.org/docs/test-utils.html as well.

**Comment by gaearon** [comment]
Where do you see this page in search results?
It shows up with the right URL for me:

<img width="468" alt="screen shot 2018-02-09 at 1 04 20 pm" src="https://user-images.githubusercontent.com/810438/36029125-cc49d218-0d99-11e8-8509-0f6c338c644b.png">

The fact that curling for it works is strange. I think this means a bug in the website.

**Comment by brianlmacdonald** [comment]
Can I call dibs on this?

**Comment by steventsao** [comment]
I am able to load the `test-utils` page using both internal and Google search. Also, shouldn't curling any path under the domain works? Lastly, because other pages like `hello-world` also returns "Page Not Found" without `.html`, is "Page Not Found" with `test-utils` still a real issue?

**Comment by halfzebra** [comment]
The static version of any nested page is available via `/pagename`, but when router kicks in, it shows "Page Not Found"

I'm not 100% sure if this is a problem, a side-effect of SEO optimization or a simple oversight.

Somehow I've gotten to https://reactjs.org/docs/test-utils and I couldn't understand why I'm getting 404 as a user, even though I can clearly see that server returns the page I have expected.

I would expect a consistent behavior such as:

- 404 from the server and on the front-end
- prevent client-side router from showing 404 if URL is missing `.html` extension.

**Comment by nilfalse** [comment]
Just a kindly reminder that Google is not the only search engine in the world.
That might have happened in any other search engine as well.
In fact, I can see the wrong search result (without `.html`) popping up in Yandex: https://yandex.com/search/?text=test-utils, though I have no idea how their crawler got to that page in the first place.

But even for Google alone it's better to have [possible] duplicate URLs consolidated.
Here is the article on Google's help website on how to do that:
https://support.google.com/webmasters/answer/139066?hl=en

I prepared the patch which adds `<link rel=canonical />`.

As per the curling working on production, this is how nginx and possibly other servers are configured by default. My bet is that whatever service is being used to serve the production website is just configured to be able to respond to both URLs with `.html` and without `.html` postfix.
There are different possible solutions work around this, I'd personally prefer changing some logic of the Router setup instead of reconfiguring web server.

**Comment by sophiebits** [comment]
I got an email from Yandex today about this. https://reactjs.org/docs/typechecking-with-proptypes returns a 200 and server-rendered content but then it updates client-side with a "Page Not Found" page.

We should either (a) make it 404 completely, or (b) make both work with a rel="canonical" tag to say which is which, or (c) add a 301 redirect from one to the other.

Would be great if someone wants to look into fixing this.

**Comment by nilfalse** [comment]
I can't see any information regarding how the docs website gets deployed and which service is being used under the hood. I assume that production website is hosted on Netlify because pull request demos get deployed to that service.

I'm not sure that (a) is even achievable because that is in fact the feature of Netlify and some other static website hostings like Github Pages that they serve `.html` pages for requests with `.html` extension as well as when the extension is omitted.

The option (c) would require to make a huge file with all possible URLs being listed.
So far [the file](/reactjs/reactjs.org/blob/master/static/_redirects) has had only 2 redirects.
I think it's better to keep that file small and maintainable.
Also whoever decides to implement this, would have to take into account the [Shadowing feature of Netlify](https://www.netlify.com/docs/redirects/#note-on-shadowing).

I can see also an option to get rid of `.html` extensions altogether.
In this case we could make only one rule for all `*.html` pages to redirect to their non-postfixed counterparts.
But that seems to be the huge change from the user's point of view.
Is there anybody who may evaluate such an option?

Given these arguments I believe (b) would be the simplest and the most straightforward.
The pull request #640 implements that option.

@sophiebits, do you know if somebody can review the pull request?
What do you think about it?

**Comment by sophiebits** [comment]
Yes, we host on Netlify in prod.

I wonder if a rule of `/*.html /:splat 301!` would implement (c) seamlessly? I might not be understanding right.

**Comment by atiqueansari1987** [comment]
Is this issue taken?

**Comment by whitedogg13** [comment]
Hi all, I think there're other way to fix this.

Actually this issue can be reproduced in any of the gatsby **dynamic** pages (or, any page created via markdown file dynamically). For example, following links will redirect to 404:

* https://reactjs.org/docs/hello-world
* https://reactjs.org/docs/hello-world/

As we can see, only https://reactjs.org/docs/hello-world.html can work correctly. The common alias we consider the same won't work.

The brute force approach for this issue might be simply modifying all *.md files for the `redirect_from` to include the **alias** paths. However, I think a better approach will be appending those **alias** paths dynamically during gatsby's `onCreateNode` hook, and I just propsed a [PR783](https://github.com/reactjs/reactjs.org/pull/783) using this approach.

Thanks!

**Comment by whitedogg13** [comment]
Hi all, update the deploy preview build for my PR #783 

https://deploy-preview-783--reactjs.netlify.com, following urls seem all OK now:

* https://deploy-preview-783--reactjs.netlify.com/docs/test-utils
* https://deploy-preview-783--reactjs.netlify.com/docs/test-utils/
* https://deploy-preview-783--reactjs.netlify.com/docs/test-utils.html

Please kindly tell me if I can further improve the PR, or should I find other way to fix the issue~
