### ISSUE TITLE
Syntax concern for ref examples

### ISSUE THREAD

**Issue by caaker** [reactjs/reactjs.org#618]
I see this pattern in the docs some time, in this case  [here, integrating with other libraries](https://reactjs.org/docs/integrating-with-other-libraries.html):

`<div ref={el => this.el = el} />
`

This will return el from the anonymous function and I wanted to verify that nothing is done with the return value.  If returning from the callback does nothing, might it be more precise to use the syntax below and avoid confusion?

`<div ref={el => {this.el = e}} />
`

**Comment by alexkrolick** [comment]
That's right, the callback's return value is ignored. There is an ESLint rule that complains about this: https://eslint.org/docs/rules/no-return-assign

Rather than changing the syntax for functional refs in the docs, we should probably migrate them to the new `createRef` syntax except in the one place where the functional form is documented.

**Comment by caaker** [comment]
According to [Mozilla Docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions)

> (param1, param2, …, paramN) => { statements } // does not return
> (param1, param2, …, paramN) => expression
> // equivalent to: => { return expression; } 

so the below implementation should not return any thing:

`<div ref={el => {this.el = el}} />
`
and it does not break any ES lint rules.

**Comment by alexkrolick** [comment]
Right, the way without `{}` breaks the return rule. Your proposal doesn't.

**Comment by caaker** [comment]
So if this line is going to be included in the future, might it be a good idea to update it to

`<div ref={el => {this.el = el}} />
`

So that users who don't know that the return value is discarded are not left thinking that b.c. there is a value returned that something is done with it.

This is what I originally though before this issue made clear that nothing is done with the returned value.

In general when you see a value returned, you might think that there is something done with it from the calling code.

**Comment by alexkrolick** [comment]
It's fine to change it, but all those examples will probably be changed over to `createRef` as soon as 16.3 is released: https://github.com/reactjs/reactjs.org/pull/587/files#diff-3e1401f3eb6a67257683926942b43373R29

There will be one example documenting the functional syntax and in that we should wrap in `{}`.

**Comment by caaker** [comment]
Sounds good!  Do you by chance know the location of that one example?  Is it the [link from above](https://github.com/reactjs/reactjs.org/issues/618) or some where else?

**Comment by alexkrolick** [comment]
https://github.com/reactjs/reactjs.org/pull/587/files
https://deploy-preview-587--reactjs.netlify.com/docs/refs-and-the-dom.html#callback-refs

It's been updated already, actually, with a function reference instead of inline.

FYI: The new example also the stored reference to be more transparently compatible with the new API, by storing the reference in `this.someRef.value` instead of `this.someRef.`

**Comment by alexkrolick** [comment]
The changes are live at https://reactjs.org/docs/refs-and-the-dom.html#callback-refs
