### ISSUE TITLE
extending components with static getDerivedStateFromProps

### ISSUE THREAD

**Issue by jozefchutka** [reactjs/reactjs.org#725]
Hi,

what are the reasons for having [getDerivedStateFromProps static](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html)? And what is the suggested way forward for components extending base ones when getDerivedStateFromProps can not be easily overriden using OOP patterns.

cheers

**Comment by gaearon** [comment]
It’s static because we want to forbid instance access and side effects in it (which were main causes of unsafe behavior in componentWillReceiveProps).

Your second question is harder to answer because you didn’t specify your language (JS? TS?) In general [we recommend against using inheritance for React components](https://reactjs.org/docs/composition-vs-inheritance.html) altogether. If you disagree with this recommendation you’ll need to find a way that works for you, but technically nothing prevents you from doing it like you normally would in JavaScript (for example by putting a static method on the descendant class, and calling the base method from it).

**Comment by gaearon** [comment]
I don't understand what you mean. You can declare functions anywhere and call them.

```js
function something() {
  // ...
}

class MyClass {
  static getDerivedStateFromProps() {
    var x = something();
    // ...
  }
  // ...
}
```

You don't need to put everything into the class itself, there's no point to it.

**Comment by iMerica** [comment]
I was trying to avoid that becomes it seems messy, but good point. Thanks @gaearon !

**Comment by gaearon** [comment]
I quite disagree it’s messy. If anything it’s better than putting implementation details onto the class because it guarantees none of the external code to the module can access it.

**Comment by iMerica** [comment]
After trying various approaches, I've decided to replace all my `getDerivedStateFromProps` functions with `componentDidUpdate()`. I'm finding this static function approach to be very limiting. Also access control of helper methods is not something that I'm concerned with in the context of a React application.

**Comment by gaearon** [comment]
In general `getDerivedStateFromProps()` [is intended for very rare use cases](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html), and you're right you probably don't need it.
