### ISSUE TITLE
warning: npm WARN deprecated isarray@2.0.1: Just use Array.isArray directly

### ISSUE THREAD

**Issue by sw-yx** [reactjs/reactjs.org#77]
when i npm install this repo i get this warning `npm WARN deprecated isarray@2.0.1: Just use Array.isArray directly` . im not sure how to track down this dependency since its not a direct dependency of this repo - any ideas on how I can get it out?

**Comment by bvaughn** [comment]
Sure! Yarn has a command `why` for just this reason:
```sh
$ yarn why isarray
Using globally installed version of Yarn
yarn why v1.0.0
[1/4] 🤔  Why do we have the module "isarray"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
info Has been hoisted to "isarray"
info Reasons this module exists
   - "eslint#doctrine" depends on it
   - "eslint#concat-stream#readable-stream" depends on it
   - "gatsby#yurnalist#markdown-toc#object.pick#isobject" depends on it
info Disk size without dependencies: "32kB"
info Disk size with unique dependencies: "32kB"
info Disk size with transitive dependencies: "32kB"
info Number of shared dependencies: 0
✨  Done in 0.86s.
```

I don't think we need an open issue for this since it's just a local, dev-warning and it won't harm anything unless we choose to upgrade our `yarn.lock` file in the future. But I'd be happy to accept a PR if you're able to chase down the fix upstream. 😄

You could try running `yarn upgrade-interactive` to see if it resolves the issue. After doing so though I'd be sure everything builds correctly from scratch:
```sh
rm -rf node_modules
rm -rf .cache
yarn install # Fresh install
yarn build # Make sure Gatsby can create a production build
cd public # Production build goes here
serve # Make sure production build works at localhost:5000
yarn dev # Make Gatsby's dev mode works at localhost:8000
```
