### ISSUE TITLE
Comment about Styling FAQ

### ISSUE THREAD

**Issue by carpben** [reactjs/reactjs.org#789]
from https://github.com/reactjs/reactjs.org/blob/master/content/docs/faq-styling.md#are-inline-styles-bad

> "CSS classes are generally more efficient than inline styles"

Do u mean it is more efficient for coding, or for the browser to handle? I find the sentence a bit unclear.

**Comment by alexkrolick** [comment]
That's correct, inline styles are bad for performance compared to CSS classNames.

**Comment by alexkrolick** [comment]
Changed to "better for performance"

**Comment by seapage** [comment]
In another place of documentation there is written

> Note
Some examples in the documentation use style for convenience, but using the style attribute as the primary means of styling elements is generally not recommended. In most cases, className should be used to reference classes defined in an external CSS stylesheet. style is most often used in React applications to add dynamically-computed styles at render time. See also FAQ: Styling and CSS.

Please add some Note to FAQ page 

> "CSS classes are generally more efficient than inline styles"

Some link for example: `read more in this article` Because for me it's to general `are generally`.
